server:
  port: 8761
spring:
  application:
    name: eureka
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    server-url:
      defaultZone: http://localhost:8761/eureka/