server:
  port: 8005
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ""
    url: jdbc:mysql://localhost:3305/cuenta?createDatabaseIfNotExist=true

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always
