server:
  port: 8004
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ""
    url: jdbc:mysql://localhost:3308/tarifa?createDatabaseIfNotExist=true
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
